language: ruby
sudo: false
bundler_args: --without development
cache: bundler

rvm:
  - 2.3.0
  - 2.4.0
  - 2.5.0
  - ruby-head
  - jruby-9.1.0.0
  - jruby-head
jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9
matrix:
  exclude:
    - rvm: 2.3.0
      jdk: oraclejdk8
    - rvm: 2.3.0
      jdk: oraclejdk9
    - rvm: 2.4.0
      jdk: oraclejdk8
    - rvm: 2.4.0
      jdk: oraclejdk9
    - rvm: 2.5.0
      jdk: oraclejdk8
    - rvm: 2.5.0
      jdk: oraclejdk9
    - rvm: ruby-head
      jdk: oraclejdk8
    - rvm: ruby-head
      jdk: oraclejdk9
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
branches:
  only:
      - master
env:
  global:
    - MONGODB_VERSION=3.2.0
    - JRUBY_OPTS="-Xcli.debug=true --debug"
before_install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - tar xfz mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - export PATH=`pwd`/mongodb-linux-x86_64-$MONGODB_VERSION/bin:$PATH
  - mkdir -p data/db
  - mongod --dbpath=data/db &> /dev/null &
  - sleep 3
before_script: ./.travis/db_prepare.sh
