language: ruby
sudo: false
bundler_args: --without development
cache: bundler

rvm:
  - 2.1.7
  - 2.2.3
  - ruby-head
  - jruby-9.0.1.0
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
matrix:
  exclude:
    - rvm: 2.1.7
      jdk: oraclejdk7
    - rvm: 2.1.7
      jdk: oraclejdk8
    - rvm: 2.2.3
      jdk: oraclejdk7
    - rvm: 2.2.3
      jdk: oraclejdk8
    - rvm: ruby-head
      jdk: oraclejdk7
    - rvm: ruby-head
      jdk: oraclejdk8
  allow_failures:
    - rvm: ruby-head
branches:
  only:
      - master
env:
  global:
    -MONGODB_VERSION=3.2.0
before_install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - tar xfz mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - export PATH=`pwd`/mongodb-linux-x86_64-$MONGODB_VERSION/bin:$PATH
  - mkdir -p data/db
  - mongod --dbpath=data/db &> /dev/null &
  - sleep 3
before_script: ./.travis/db_prepare.sh
