language: ruby
sudo: false
bundler_args: --without development
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
  - jruby-9.1
  - jruby-head
jdk:
  - openjdk8
  - openjdk10
  - openjdk11
matrix:
  exclude:
    - rvm: 2.3
      jdk: openjdk10
    - rvm: 2.3
      jdk: openjdk11
    - rvm: 2.4
      jdk: openjdk10
    - rvm: 2.4
      jdk: openjdk11
    - rvm: 2.5
      jdk: openjdk10
    - rvm: 2.5
      jdk: openjdk11
    - rvm: 2.6
      jdk: openjdk10
    - rvm: 2.6
      jdk: openjdk11
    - rvm: ruby-head
      jdk: openjdk10
    - rvm: ruby-head
      jdk: openjdk11
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
branches:
  only:
      - master
env:
  global:
    - MONGODB_VERSION=3.2.0
    - JRUBY_OPTS="-Xcli.debug=true --debug"
before_install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - tar xfz mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - export PATH=`pwd`/mongodb-linux-x86_64-$MONGODB_VERSION/bin:$PATH
  - mkdir -p data/db
  - mongod --dbpath=data/db &> /dev/null &
  - sleep 3
before_script: ./.travis/db_prepare.sh
